{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d41ae169",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Selected folder: E:/ImpLoadTest-01/D-868-7.14_Cropped\n",
      "Global scaling factor (X): 0.84 mm/px\n",
      "Global scaling factor (Y): 0.82 mm/px\n"
     ]
    }
   ],
   "source": [
    "##############################################################################\n",
    "                        # LIBRARY IMPORTS\n",
    "##############################################################################\n",
    "\n",
    "import cv2\n",
    "import numpy as np\n",
    "import math\n",
    "import os\n",
    "import re\n",
    "import tkinter as tk\n",
    "from tkinter import messagebox, simpledialog\n",
    "from tkinter import filedialog\n",
    "\n",
    "##############################################################################\n",
    "                        # GLOBAL VARIABLES & CONSTANTS\n",
    "##############################################################################\n",
    "\n",
    "NUM_SCALING_IMAGES = 13  \n",
    "image_files = []\n",
    "current_image_index = 0\n",
    "image = None\n",
    "crack_image_on_bright = None\n",
    "zoom_factor = 5  \n",
    "is_zoomed = False\n",
    "mouse_x, mouse_y = 0, 0\n",
    "distance_mode = False\n",
    "compute_cell_area_mode = False  \n",
    "polygon_mode = False            \n",
    "clicked_points = []             \n",
    "polygon_points = []             \n",
    "roi_x1, roi_y1 = 0, 0         \n",
    "small_box_size_mm = 100  \n",
    "scaling_factor_width = False\n",
    "scaling_factor_height = False\n",
    "distance_text = \"\"  \n",
    "grid_spacing_mm = 100  \n",
    "drag_start = None \n",
    "drag_end = None\n",
    "highlighted_cell = None\n",
    "displacement_x = 0.0 \n",
    "\n",
    "##############################################################################\n",
    "                        # HELPER FUNCTIONS\n",
    "##############################################################################\n",
    "\n",
    "def draw_transparent_rectangle(img, x, y, w, h, color=(0,55,0), alpha=0.2):\n",
    "    overlay = img.copy()\n",
    "    cv2.rectangle(overlay, (x, y), (x + w, y + h), color, -1)\n",
    "    cv2.addWeighted(overlay, alpha, img, 1 - alpha, 0, img)\n",
    "\n",
    "def perspective_correction(img, contour):\n",
    "    epsilon = 0.05 * cv2.arcLength(contour, True)\n",
    "    approx = cv2.approxPolyDP(contour, epsilon, True)\n",
    "    if len(approx) == 4:\n",
    "        pts = sorted(np.squeeze(approx), key=lambda x: (x[1], x[0]))\n",
    "        pts1 = np.float32([pts[0], pts[1], pts[3], pts[2]])\n",
    "        width, height = 100, 100\n",
    "        pts2 = np.float32([[0, 0], [width, 0], [width, height], [0, height]])\n",
    "        matrix = cv2.getPerspectiveTransform(pts1, pts2)\n",
    "        return cv2.warpPerspective(img, matrix, (width, height))\n",
    "    return None\n",
    "\n",
    "def detect_scaling_factors_in_image(img_gray):\n",
    "    blurred = cv2.GaussianBlur(img_gray, (5,5), 0)\n",
    "    adaptive_thresh = cv2.adaptiveThreshold(blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\n",
    "                                              cv2.THRESH_BINARY_INV, 11, 2)\n",
    "    contours, _ = cv2.findContours(adaptive_thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)\n",
    "    found_factors = []\n",
    "    for contour in contours:\n",
    "        x, y, w, h = cv2.boundingRect(contour)\n",
    "        aspect_ratio = w / float(h)\n",
    "        area = cv2.contourArea(contour)\n",
    "        if 0.9 < aspect_ratio < 1.1 and 1000 < area < 20000:\n",
    "            corrected_box = perspective_correction(img_gray, contour)\n",
    "            if corrected_box is not None:\n",
    "                sfx = small_box_size_mm / w\n",
    "                sfy = small_box_size_mm / h\n",
    "                found_factors.append((sfx, sfy))\n",
    "    return found_factors\n",
    "\n",
    "\n",
    "##############################################################################\n",
    "                        # FILENAME SORTING FUNCTION\n",
    "##############################################################################\n",
    "\n",
    "def numeric_key(path):\n",
    "    filename = os.path.basename(path)\n",
    "    match = re.search(r'\\((\\d+)\\)', filename)\n",
    "    return int(match.group(1)) if match else 999999\n",
    "\n",
    "##############################################################################\n",
    "                        # COMPUTE AVERAGE SCALING FACTOR\n",
    "##############################################################################\n",
    "\n",
    "def compute_average_scaling_factor_for_folder(folder_path):\n",
    "    all_sfx = []\n",
    "    all_sfy = []\n",
    "    all_files = [os.path.join(folder_path, f) for f in os.listdir(folder_path)\n",
    "                 if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff'))]\n",
    "    all_files = sorted(all_files, key=numeric_key)\n",
    "    num_images = min(NUM_SCALING_IMAGES, len(all_files))\n",
    "    for img_path in all_files[:num_images]:\n",
    "        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)\n",
    "        if img is None:\n",
    "            continue\n",
    "        factors = detect_scaling_factors_in_image(img)\n",
    "        if factors:\n",
    "            for (sfx, sfy) in factors:\n",
    "                all_sfx.append(sfx)\n",
    "                all_sfy.append(sfy)\n",
    "    if len(all_sfx) == 0:\n",
    "        return None, None\n",
    "    avg_sfx = np.mean(all_sfx)\n",
    "    avg_sfy = np.mean(all_sfy)\n",
    "    return avg_sfx, avg_sfy\n",
    "\n",
    "# Function to prompt the user to set the grid displacement\n",
    "def set_displacement():\n",
    "    displacement_value = simpledialog.askfloat(\"Grid Displacement\", \"Enter displacement in mm:\", initialvalue=0.0)\n",
    "    if displacement_value is not None:\n",
    "        print(f\"Displacement set to: {displacement_value} mm\")\n",
    "        return displacement_value\n",
    "    return 0.0\n",
    "# Function to convert displacement in mm to pixels using scaling factor\n",
    "def convert_displacement_to_pixels(displacement_mm, scaling_factor):\n",
    "    return int(displacement_mm / scaling_factor)\n",
    "\n",
    "\n",
    "##############################################################################\n",
    "                        # LOAD IMAGE FUNCTIONS\n",
    "##############################################################################\n",
    "\n",
    "def load_folder(folder_path):\n",
    "    global image_files, current_image_index, scaling_factor_width, scaling_factor_height\n",
    "    image_files = [os.path.join(folder_path, f) for f in os.listdir(folder_path)\n",
    "                   if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff'))]\n",
    "    image_files = sorted(image_files, key=numeric_key)\n",
    "    if not image_files:\n",
    "        messagebox.showerror(\"Error\", \"No image files found in the specified folder.\")\n",
    "        return\n",
    "    avg_sfx, avg_sfy = compute_average_scaling_factor_for_folder(folder_path)\n",
    "    if avg_sfx is not None:\n",
    "        scaling_factor_width = avg_sfx\n",
    "        scaling_factor_height = avg_sfy\n",
    "        print(f\"Global scaling factor (X): {scaling_factor_width:.2f} mm/px\")\n",
    "        print(f\"Global scaling factor (Y): {scaling_factor_height:.2f} mm/px\")\n",
    "    else:\n",
    "        scaling_factor_width = scaling_factor_height = None\n",
    "        messagebox.showerror(\"Error\", \"No suitable scaling boxes found in the folder.\")\n",
    "    current_image_index = 0\n",
    "    load_image()\n",
    "\n",
    "def load_image():\n",
    "    global image, crack_image_on_bright, highlighted_cell, polygon_points, polygon_mode\n",
    "    if current_image_index >= len(image_files):\n",
    "        messagebox.showinfo(\"End\", \"All images in the folder have been processed.\")\n",
    "        return\n",
    "    image_path = image_files[current_image_index]\n",
    "    img = cv2.imread(image_path)\n",
    "    if img is None:\n",
    "        messagebox.showerror(\"Error\", f\"Image at path '{image_path}' could not be loaded.\")\n",
    "        return\n",
    "    highlighted_cell = None\n",
    "    polygon_points = []\n",
    "    polygon_mode = False\n",
    "    reset_main_image(img)\n",
    "\n",
    "def reset_main_image(new_img):\n",
    "    global image\n",
    "    image = new_img\n",
    "    process_image()\n",
    "\n",
    "##############################################################a################\n",
    "                        # IMAGE PROCESSING FUNCTIONS\n",
    "##############################################################################\n",
    "\n",
    "def remove_grid_lines(img):\n",
    "    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "    adaptive_thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C,\n",
    "                                              cv2.THRESH_BINARY_INV, 15, 10)\n",
    "    vertical_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1,30))\n",
    "    horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (30,1))\n",
    "    vertical_lines = cv2.morphologyEx(adaptive_thresh, cv2.MORPH_OPEN, vertical_kernel)\n",
    "    horizontal_lines = cv2.morphologyEx(adaptive_thresh, cv2.MORPH_OPEN, horizontal_kernel)\n",
    "    grid_mask = cv2.bitwise_or(vertical_lines, horizontal_lines)\n",
    "    dilated_grid_mask = cv2.dilate(grid_mask, np.ones((3,3), np.uint8), iterations=2)\n",
    "    img_no_grid = cv2.inpaint(img, dilated_grid_mask, 5, cv2.INPAINT_TELEA)\n",
    "    return img_no_grid\n",
    "\n",
    "def detect_cracks_no_area(image_no_grid):\n",
    "    gray_image = cv2.cvtColor(image_no_grid, cv2.COLOR_BGR2GRAY)\n",
    "    brightened_image = cv2.convertScaleAbs(gray_image, alpha=0.68, beta=12)\n",
    "    _, binary_image = cv2.threshold(brightened_image, 85, 255, cv2.THRESH_BINARY_INV)\n",
    "    contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
    "    crack_image = image_no_grid.copy()\n",
    "    cv2.drawContours(crack_image, contours, -1, (0,0,255), 2)\n",
    "    return crack_image\n",
    "\n",
    "def process_image():\n",
    "    global image, crack_image_on_bright, scaling_factor_width, scaling_factor_height\n",
    "    if current_image_index < NUM_SCALING_IMAGES:\n",
    "        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)\n",
    "        gray = cv2.equalizeHist(gray)\n",
    "        blurred = cv2.GaussianBlur(gray, (5,5), 0)\n",
    "        adaptive_thresh = cv2.adaptiveThreshold(blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\n",
    "                                                  cv2.THRESH_BINARY_INV, 11, 2)\n",
    "        contours, _ = cv2.findContours(adaptive_thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)\n",
    "        for contour in contours:\n",
    "            x, y, w, h = cv2.boundingRect(contour)\n",
    "            aspect_ratio = w / float(h)\n",
    "            area = cv2.contourArea(contour)\n",
    "            if 0.9 < aspect_ratio < 1.1 and 1000 < area < 20000:\n",
    "                corrected_box = perspective_correction(gray, contour)\n",
    "                if corrected_box is not None:\n",
    "                    draw_transparent_rectangle(image, x, y, w, h)\n",
    "    if scaling_factor_width and scaling_factor_height:\n",
    "        cv2.putText(image, f'Scaling Factor X: {scaling_factor_width:.2f} mm/px', (20,30),\n",
    "                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)\n",
    "        cv2.putText(image, f'Scaling Factor Y: {scaling_factor_height:.2f} mm/px', (20,50),\n",
    "                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)\n",
    "    image_no_grid = remove_grid_lines(image)\n",
    "    crack_image_on_bright = detect_cracks_no_area(image_no_grid)\n",
    "\n",
    "##############################################################################\n",
    "                    # CALCULATION & GRID FUNCTIONS\n",
    "##############################################################################\n",
    "\n",
    "def calculate_distance(point1, point2, scaling_factor_x, scaling_factor_y):\n",
    "    dx = (point2[0] - point1[0]) * scaling_factor_x if scaling_factor_x else 0\n",
    "    dy = (point2[1] - point1[1]) * scaling_factor_y if scaling_factor_y else 0\n",
    "    return math.sqrt(dx**2 + dy**2)\n",
    "\n",
    "def compute_polygon_area(points):\n",
    "    if len(points) < 3:\n",
    "        return 0\n",
    "    pts = np.array(points, dtype=np.int32)\n",
    "    area_px = cv2.contourArea(pts)\n",
    "    if scaling_factor_width and scaling_factor_height:\n",
    "        area_mm2 = area_px * (scaling_factor_width * scaling_factor_height)\n",
    "        return area_mm2\n",
    "    return area_px\n",
    "\n",
    "# Modified function to draw grid with horizontal displacement\n",
    "def draw_grid_on_image(img, grid_spacing_x=50, grid_spacing_y=50, displacement_x=0):\n",
    "    img_with_grid = img.copy()\n",
    "    h, w = img_with_grid.shape[:2]\n",
    "    \n",
    "    # Apply displacement to the grid horizontally\n",
    "    for y in range(0, h, grid_spacing_y):\n",
    "        cv2.line(img_with_grid, (displacement_x, y), (w + displacement_x, y), (0,0,0), 1)\n",
    "    \n",
    "    for x in range(0, w, grid_spacing_x):\n",
    "        cv2.line(img_with_grid, (x + displacement_x, 0), (x + displacement_x, h), (0,0,0), 1)\n",
    "    \n",
    "    box_number = 1\n",
    "    rows = h // grid_spacing_y\n",
    "    cols = w // grid_spacing_x\n",
    "    for row in range(rows):\n",
    "        for col in range(cols):\n",
    "            cell_x = col * grid_spacing_x + displacement_x\n",
    "            cell_y = row * grid_spacing_y\n",
    "            center_x = cell_x + grid_spacing_x // 2\n",
    "            center_y = cell_y + grid_spacing_y // 2\n",
    "            cv2.putText(img_with_grid, str(box_number),\n",
    "                        (center_x - 10, center_y + 5),\n",
    "                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1)\n",
    "            box_number += 1\n",
    "    \n",
    "    return img_with_grid\n",
    "\n",
    "# Global variables to store the crack areas for the current and previous image\n",
    "previous_image_areas = {}\n",
    "\n",
    "# Function to compute the cracked area in each cell and track changes\n",
    "# Define the threshold for significant change in pixels\n",
    "significant_change_threshold = 1  # Change in pixels that is considered significant\n",
    "\n",
    "def compute_cell_area(x, y):\n",
    "    global crack_image_on_bright, grid_spacing_mm, scaling_factor_width, scaling_factor_height, highlighted_cell\n",
    "    src = crack_image_on_bright if crack_image_on_bright is not None else image\n",
    "    \n",
    "    # Cell size in pixels based on scaling factors\n",
    "    if scaling_factor_width and scaling_factor_height:\n",
    "        cell_width_px = int(grid_spacing_mm / scaling_factor_width)\n",
    "        cell_height_px = int(grid_spacing_mm / scaling_factor_height)\n",
    "    else:\n",
    "        cell_width_px = cell_height_px = 50\n",
    "\n",
    "    col = x // cell_width_px\n",
    "    row = y // cell_width_px\n",
    "    x1 = col * cell_width_px\n",
    "    y1 = row * cell_height_px\n",
    "    x2 = x1 + cell_width_px\n",
    "    y2 = y1 + cell_height_px\n",
    "    cell = src[y1:y2, x1:x2].copy()\n",
    "    \n",
    "    # Convert the selected cell to grayscale for processing\n",
    "    gray_cell = cv2.cvtColor(cell, cv2.COLOR_BGR2GRAY)\n",
    "    _, binary_cell = cv2.threshold(gray_cell, 85, 255, cv2.THRESH_BINARY_INV)\n",
    "    \n",
    "    # Get the total and white (crack) pixels\n",
    "    total_pixels = binary_cell.size\n",
    "    white_pixels = cv2.countNonZero(binary_cell)\n",
    "    black_pixels = total_pixels - white_pixels\n",
    "    \n",
    "    # Calculate the cracked area in pixels and millimeters (if scaling factors are available)\n",
    "    if scaling_factor_width and scaling_factor_height:\n",
    "        px_to_mm2 = scaling_factor_width * scaling_factor_height\n",
    "        crack_area_mm2 = white_pixels * px_to_mm2\n",
    "        non_crack_area_mm2 = black_pixels * px_to_mm2\n",
    "        crack_percent = (crack_area_mm2 / (total_pixels * px_to_mm2)) * 100 if total_pixels > 0 else 0\n",
    "        non_crack_percent = 100 - crack_percent\n",
    "        print(f\"Cell ({row}, {col}):\")\n",
    "        print(f\"  Crack Area (Black): {white_pixels} px, {crack_area_mm2:.2f} mm² ({crack_percent:.1f}%)\")\n",
    "        print(f\"  Non-Crack Area (White): {black_pixels} px, {non_crack_area_mm2:.2f} mm² ({non_crack_percent:.1f}%)\")\n",
    "    else:\n",
    "        crack_percent = (white_pixels / total_pixels) * 100 if total_pixels > 0 else 0\n",
    "        non_crack_percent = 100 - crack_percent\n",
    "        print(f\"Cell ({row}, {col}):\")\n",
    "        print(f\"  Crack Area (Black): {white_pixels} px ({crack_percent:.1f}%), Non-Crack Area (White): {black_pixels} px ({non_crack_percent:.1f}%)\")\n",
    "    \n",
    "    # Highlight the selected cell on the image\n",
    "    highlighted_cell = (x1, y1, x2, y2)\n",
    "    \n",
    "    # Track the crack area for this cell in the current image\n",
    "    area_data = {\n",
    "        \"crack_area_px\": white_pixels,\n",
    "        \"crack_area_mm2\": crack_area_mm2 if scaling_factor_width and scaling_factor_height else None\n",
    "    }\n",
    "    \n",
    "    # Get the key for this cell\n",
    "    cell_key = (row, col)\n",
    "\n",
    "    # If it's not the first image, compare with previous areas\n",
    "    if previous_image_areas.get(cell_key) is not None:\n",
    "        prev_area = previous_image_areas[cell_key][\"crack_area_px\"]\n",
    "        area_change = white_pixels - prev_area\n",
    "\n",
    "        # If the change is below the threshold, ignore it and print \"No significant change\"\n",
    "        if abs(area_change) < significant_change_threshold:\n",
    "            print(f\"No significant change in cracked area for Cell ({row}, {col}).\")\n",
    "        else:\n",
    "            print(f\"Change in cracked area for Cell ({row}, {col}): {area_change} pixels.\")\n",
    "    else:\n",
    "        print(f\"Change in crack area in this Cell ({row}, {col}), same as cracked area.\")\n",
    "    \n",
    "    # Store current area for next image comparison\n",
    "    previous_image_areas[cell_key] = area_data\n",
    "    highlighted_cell = (x1, y1, x2, y2)  # Highlight the clicked cell\n",
    "\n",
    "\n",
    "\n",
    "# Add the `c` button functionality to activate the mode\n",
    "def on_key_press(event):\n",
    "    global compute_cell_area_mode\n",
    "    if event.char == 'c':\n",
    "        compute_cell_area_mode = not compute_cell_area_mode\n",
    "        if compute_cell_area_mode:\n",
    "            print(\"Cell Area Mode ON\")\n",
    "        else:\n",
    "            print(\"Cell Area Mode OFF\")\n",
    "\n",
    "##############################################################################\n",
    "                        # MOUSE & MAIN LOOP FUNCTIONS\n",
    "##############################################################################\n",
    "\n",
    "def on_mouse(event, x, y, flags, param):\n",
    "    global mouse_x, mouse_y, clicked_points, is_zoomed, drag_start, drag_end\n",
    "    global distance_mode, distance_text, compute_cell_area_mode, polygon_mode, polygon_points, highlighted_cell\n",
    "\n",
    "    if polygon_mode:\n",
    "        if event == cv2.EVENT_LBUTTONDOWN:\n",
    "            if is_zoomed:\n",
    "                h_img, w_img = image.shape[:2]\n",
    "                crop_w = int(w_img / zoom_factor)\n",
    "                crop_h = int(h_img / zoom_factor)\n",
    "                adjusted_x = roi_x1 + int(x * crop_w / w_img)\n",
    "                adjusted_y = roi_y1 + int(y * crop_h / h_img)\n",
    "            else:\n",
    "                adjusted_x, adjusted_y = x, y\n",
    "            polygon_points.append((adjusted_x, adjusted_y))\n",
    "            cv2.circle(image, (adjusted_x, adjusted_y), 4, (255,0,0), -1)\n",
    "            if len(polygon_points) > 1:\n",
    "                cv2.line(image, polygon_points[-2], polygon_points[-1], (255,0,0), 2)\n",
    "            cv2.imshow(\"Crack Detection\", image)\n",
    "            return\n",
    "        elif event == cv2.EVENT_RBUTTONDOWN:\n",
    "            if len(polygon_points) >= 3:\n",
    "                cv2.line(image, polygon_points[-1], polygon_points[0], (255,0,0), 2)\n",
    "                area = compute_polygon_area(polygon_points)\n",
    "                text = f\"Poly Area: {area:.2f} mm^2\" if (scaling_factor_width and scaling_factor_height) else f\"Poly Area: {area:.2f} px\"\n",
    "                print(text)\n",
    "                cv2.putText(image, text, (polygon_points[0][0], polygon_points[0][1]-10),\n",
    "                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,0,0),2)\n",
    "                cv2.imshow(\"Crack Detection\", image)\n",
    "            polygon_mode = False\n",
    "            polygon_points = []\n",
    "            return\n",
    "\n",
    "    if compute_cell_area_mode and event == cv2.EVENT_LBUTTONDOWN:\n",
    "        compute_cell_area(x, y)\n",
    "        return\n",
    "\n",
    "    if event == cv2.EVENT_MOUSEMOVE:\n",
    "        mouse_x, mouse_y = x, y\n",
    "        if drag_start:\n",
    "            drag_end = (x, y)\n",
    "    elif event == cv2.EVENT_LBUTTONDOWN:\n",
    "        if is_zoomed:\n",
    "            h_img, w_img = image.shape[:2]\n",
    "            crop_w = int(w_img / zoom_factor)\n",
    "            crop_h = int(h_img / zoom_factor)\n",
    "            adjusted_x = roi_x1 + int(x * crop_w / w_img)\n",
    "            adjusted_y = roi_y1 + int(y * crop_h / h_img)\n",
    "        else:\n",
    "            adjusted_x, adjusted_y = x, y\n",
    "\n",
    "        if distance_mode:\n",
    "            if len(clicked_points) == 2:\n",
    "                clicked_points.clear()\n",
    "                idx_img = cv2.imread(image_files[current_image_index])\n",
    "                if idx_img is not None:\n",
    "                    reset_main_image(idx_img)\n",
    "            clicked_points.append((adjusted_x, adjusted_y))\n",
    "            if len(clicked_points) == 1:\n",
    "                cv2.circle(image, (adjusted_x, adjusted_y), 5, (0,0,255), -1)\n",
    "            elif len(clicked_points) == 2:\n",
    "                cv2.circle(image, (adjusted_x, adjusted_y), 5, (0,0,255), -1)\n",
    "                cv2.line(image, clicked_points[0], (adjusted_x, adjusted_y), (0,255,0),2)\n",
    "                dist = calculate_distance(clicked_points[0], (adjusted_x, adjusted_y),\n",
    "                                          scaling_factor_width, scaling_factor_height)\n",
    "                distance_text = f\"Distance: {dist:.2f} mm\"\n",
    "            cv2.imshow(\"Crack Detection\", image)\n",
    "            return\n",
    "\n",
    "        if drag_start is None:\n",
    "            drag_start = (x, y)\n",
    "            drag_end = None\n",
    "\n",
    "    elif event == cv2.EVENT_LBUTTONUP:\n",
    "        if drag_start:\n",
    "            x1, y1 = drag_start\n",
    "            x2, y2 = x, y\n",
    "            width = abs(x2 - x1)\n",
    "            height = abs(y2 - y1)\n",
    "            if scaling_factor_width and scaling_factor_height:\n",
    "                area_pixels = width * height\n",
    "                area_mm2 = area_pixels * scaling_factor_width * scaling_factor_height\n",
    "                print(f\"Selected Area: {area_mm2:.2f} mm²\")\n",
    "            else:\n",
    "                print(\"Selected Area: (No scaling factor)\")\n",
    "            drag_start = None\n",
    "\n",
    "# Main loop function to handle keypresses directly within the loop:\n",
    "def main_loop():\n",
    "    global image, crack_image_on_bright, current_image_index, is_zoomed, distance_mode\n",
    "    global roi_x1, roi_y1, distance_text, compute_cell_area_mode, highlighted_cell, grid_spacing_mm\n",
    "    global polygon_mode, polygon_points, displacement_x  # Added displacement_x to globals\n",
    "\n",
    "    if image is None:\n",
    "        messagebox.showerror(\"Error\", \"No image loaded. Please check the folder path.\")\n",
    "        return\n",
    "\n",
    "    cv2.namedWindow(\"Crack Detection\")\n",
    "    cv2.setMouseCallback(\"Crack Detection\", on_mouse)\n",
    "\n",
    "    while True:\n",
    "        h, w = image.shape[:2]\n",
    "        if crack_image_on_bright is not None:\n",
    "            base_display = cv2.addWeighted(image, 0.7, crack_image_on_bright, 0.3, 0)\n",
    "        else:\n",
    "            base_display = image.copy()\n",
    "\n",
    "        if is_zoomed:\n",
    "            crop_w = int(w / zoom_factor)\n",
    "            crop_h = int(h / zoom_factor)\n",
    "            zoom_x1 = max(0, min(mouse_x - crop_w // 2, w - crop_w))\n",
    "            zoom_y1 = max(0, min(mouse_y - crop_h // 2, h - crop_h))\n",
    "            roi_x1, roi_y1 = zoom_x1, zoom_y1\n",
    "            if scaling_factor_width and scaling_factor_height:\n",
    "                grid_spacing_x = int(grid_spacing_mm / scaling_factor_width)\n",
    "                grid_spacing_y = int(grid_spacing_mm / scaling_factor_height)\n",
    "            else:\n",
    "                grid_spacing_x = grid_spacing_y = 80\n",
    "\n",
    "            full_grid = draw_grid_on_image(image,\n",
    "                                           grid_spacing_x=grid_spacing_x,\n",
    "                                           grid_spacing_y=grid_spacing_y,\n",
    "                                           displacement_x=convert_displacement_to_pixels(displacement_x, scaling_factor_width))\n",
    "            grid_crop = full_grid[zoom_y1:zoom_y1+crop_h, zoom_x1:zoom_x1+crop_w]\n",
    "            grid_resized = cv2.resize(grid_crop, (w, h), interpolation=cv2.INTER_LINEAR)\n",
    "            crop = base_display[zoom_y1:zoom_y1+crop_h, zoom_x1:zoom_x1+crop_w]\n",
    "            display_image = cv2.resize(crop, (w, h), interpolation=cv2.INTER_LINEAR)\n",
    "            display_image = cv2.addWeighted(display_image, 0.9, grid_resized, 0.1, 0)\n",
    "            if highlighted_cell is not None:\n",
    "                hx1, hy1, hx2, hy2 = highlighted_cell\n",
    "                new_hx1 = int((hx1 - roi_x1) * w / crop_w)\n",
    "                new_hy1 = int((hy1 - roi_y1) * h / crop_h)\n",
    "                new_hx2 = int((hx2 - roi_x1) * w / crop_w)\n",
    "                new_hy2 = int((hy2 - roi_y1) * h / crop_h)\n",
    "                cv2.rectangle(display_image, (new_hx1, new_hy1), (new_hx2, new_hy2), (0,0,255), 3)\n",
    "        else:\n",
    "            display_image = base_display.copy()\n",
    "            if highlighted_cell is not None:\n",
    "                cv2.rectangle(display_image,\n",
    "                              (highlighted_cell[0], highlighted_cell[1]),\n",
    "                              (highlighted_cell[2], highlighted_cell[3]),\n",
    "                              (0,0,255), 3)\n",
    "            if scaling_factor_width and scaling_factor_height:\n",
    "                grid_spacing_x = int(grid_spacing_mm / scaling_factor_width)\n",
    "                grid_spacing_y = int(grid_spacing_mm / scaling_factor_height)\n",
    "            else:\n",
    "                grid_spacing_x = grid_spacing_y = 80\n",
    "            display_image = draw_grid_on_image(display_image,\n",
    "                                               grid_spacing_x=grid_spacing_x,\n",
    "                                               grid_spacing_y=grid_spacing_y,\n",
    "                                               displacement_x=convert_displacement_to_pixels(displacement_x, scaling_factor_width))\n",
    "\n",
    "        cv2.imshow(\"Crack Detection\", display_image)\n",
    "        \n",
    "        key = cv2.waitKey(1) & 0xFF\n",
    "       \n",
    "        if key == ord('n'):\n",
    "            current_image_index += 1\n",
    "            if current_image_index < len(image_files):\n",
    "                load_image()\n",
    "            else:\n",
    "                print(\"End of images in folder.\")\n",
    "        elif key == ord('b'):\n",
    "            current_image_index = max(0, current_image_index - 1)\n",
    "            load_image()\n",
    "        elif key == ord('m'):\n",
    "            is_zoomed = not is_zoomed\n",
    "        elif key == ord('d'):\n",
    "            distance_mode = not distance_mode\n",
    "        elif key == ord('c'):\n",
    "            compute_cell_area_mode = not compute_cell_area_mode\n",
    "            if not compute_cell_area_mode:\n",
    "                highlighted_cell = None\n",
    "            print(\"Cell Area Mode ON\" if compute_cell_area_mode else \"Cell Area Mode OFF\")\n",
    "        elif key == ord('p'):\n",
    "            polygon_mode = not polygon_mode\n",
    "            if polygon_mode:\n",
    "                polygon_points = []\n",
    "                print(\"Polygon mode ON: Left-click to add vertices, right-click to finish.\")\n",
    "            else:\n",
    "                print(\"Polygon mode OFF.\")\n",
    "        elif key == ord('g'):\n",
    "            new_spacing = simpledialog.askfloat(\"Grid Spacing\", \"Enter grid spacing in mm:\", initialvalue=grid_spacing_mm)\n",
    "            if new_spacing is not None and new_spacing > 0:\n",
    "                grid_spacing_mm = new_spacing\n",
    "        elif key == ord('h'):\n",
    "            # This is where the displacement is asked\n",
    "            displacement_x = simpledialog.askfloat(\"Grid Displacement\", \"Enter horizontal displacement (in pixels):\", initialvalue=0)\n",
    "            print(f\"Grid displacement set to: {displacement_x} pixels\")\n",
    "        elif key == ord('q'):\n",
    "            break\n",
    "\n",
    "    cv2.destroyAllWindows()\n",
    "\n",
    "\n",
    "##############################################################################\n",
    "                                # MAIN BLOCK\n",
    "##############################################################################\n",
    "\n",
    "def select_folder():\n",
    "    folder_selected = filedialog.askdirectory(title=\"Select Folder\")\n",
    "    if folder_selected:\n",
    "        print(f\"Selected folder: {folder_selected}\")\n",
    "        return folder_selected\n",
    "    else:\n",
    "        print(\"No folder selected\")\n",
    "        return None\n",
    "\n",
    "folder_path = select_folder() \n",
    "if folder_path:\n",
    "    load_folder(folder_path)\n",
    "    main_loop()\n",
    "else:\n",
    "    messagebox.showerror(\"Error\", \"No folder selected.\")\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e59461ca",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (anaconda3)",
   "language": "python",
   "name": "anaconda3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
